# Generated by Django 3.1.12 on 2025-07-21 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20250721_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='Age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='other', max_length=10),
        ),
    ]
