# Generated by Django 5.2.4 on 2025-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20250721_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmark',
            name='subject',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testmark',
            name='test_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='testmark',
            index=models.Index(fields=['student', 'test_name', 'subject'], name='website_tes_student_96f13e_idx'),
        ),
        migrations.AddIndex(
            model_name='testmark',
            index=models.Index(fields=['created_by', 'created_at'], name='website_tes_created_0c8130_idx'),
        ),
    ]
